apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
  - name: "8282"
    port: 8282
    targetPort: 8282
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
