apiVersion: v1
kind: Service
metadata:
     name: service-nodeport
     labels:
       io.kompose.service: app
       app: app
spec:
     ports:
     - port: 8282
       targetPort: 8282
       protocol: TCP
     selector:
       io.kompose.service: app
     type: NodePort
